<a href="https://colab.research.google.com/github/ParusSlava/Analysis_Cafe_Sales-/blob/main/EDA_Cafe_Sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Analysis Cafe Sales

*Cafe Sales - Dirty Data for Cleaning Training*

**Overview**

The Dirty Cafe Sales dataset contains 10,000 rows of synthetic data representing sales transactions in a cafe. This dataset is intentionally "dirty," with missing values, inconsistent data, and errors introduced to provide a realistic scenario for data cleaning and exploratory data analysis (EDA). It can be used to practice cleaning techniques, data wrangling, and feature engineering.

**File Information**
 - File Name: dirty_cafe_sales.csv
 - Number of Rows: 10,000
 - Number of Columns: 8



-  `Transaction ID`	- A unique identifier for each transaction. Always present and unique.
- `Item` -	The name of the item purchased. May contain missing or invalid values (e.g., "ERROR").  

- `Quantity` -	The quantity of the item purchased. May contain missing or invalid values.

- `Price Per Unit` -	The price of a single unit of the item. May contain missing or invalid values.

- `Total Spent` - 	The total amount spent on the transaction. Calculated as Quantity * Price Per Unit.	  

- `Payment Method` - 	The method of payment used. May contain missing or invalid values (e.g., None, "UNKNOWN").  

- `Location` - 	The location where the transaction occurred. May contain missing or invalid values.  

- `Transaction Date ` -	The date of the transaction. May contain missing or incorrect values.

`!pip install numpy pandas matplotlib`

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Loading the dataset / Завантаження датасету

In [ ]:
url = 'https://raw.githubusercontent.com/ParusSlava/Analysis_Cafe_Sales-/refs/heads/main/data/dirty_cafe_sales.csv'

df_origin = pd.read_csv(url)
df_origin.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [ ]:
df = df_origin.copy()

## Primary diagnosis / Первинна діагностика

In [ ]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [ ]:
print('Data type (raw):\n')
df.dtypes

Data type (raw):

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

Problem:
-  Numeric columns (Quantity, Price Per Unit, Total Spent)
-  Date columns (Transaction Date)

In [ ]:
print('Missing values:\n')
missing = df.isnull().sum()
missing_pct = (missing / len(df) *100).round()
missing_report = pd.DataFrame({
    'count': missing,
    '%': missing_pct
})
missing_report[missing_report['count'] > 0]

Missing values:

                  count     %
Item                333   3.0
Quantity            138   1.0
Price Per Unit      179   2.0
Total Spent         173   2.0
Payment Method     2579  26.0
Location           3265  33.0
Transaction Date    159   2.0

In [ ]:
print('Unique values:\n')

print('---Item---\n')
# print(df['Item'].value_counts(dropna=False))
display(df['Item'].value_counts(dropna=False))

print('\n---Payment Method---\n')
display(df['Payment Method'].value_counts(dropna=False))

print('\n---Location---\n')
display(df['Location'].value_counts(dropna=False))

Unique values:

---Item---

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
NaN          333
ERROR        292
Name: count, dtype: int64

---Payment Method---

Payment Method
NaN               2579
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

---Location---

Location
NaN         3265
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

In [ ]:
print('Find lines with "ERROR" or "UNKNOWN"\n')
# df.isin(["ERROR" or "UNKNOWN"]).any()
display(df.isin(["ERROR" or "UNKNOWN"]).any())
mask_error = df.isin(["ERROR","UNKNOWN"]).any(axis=1)
print(f'\nFind lines with "ERROR" or "UNKNOWN": {mask_error.sum()}')

Find lines with "ERROR" or "UNKNOWN"

Transaction ID      False
Item                 True
Quantity             True
Price Per Unit       True
Total Spent          True
Payment Method       True
Location             True
Transaction Date     True
dtype: bool

Find lines with "ERROR" or "UNKNOWN": 2845